version: "3"
services:
  server:
    build: ./server
    env_file: ./server/.env.sample
    ports:
      - 8080:8080
    networks:
      - backend
      - frontend

  nginx:
    build: ./client
    env_file: ./client/.env.sample
    ports:
      - 3000:3000
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
